// For authoring Nightwatch tests, see
// http://nightwatchjs.org/guide#usage

module.exports = {
  'default e2e tests': function (browser) {
    // automatically uses dev Server port from /config.index.js
    // default: http://localhost:8080
    // see nightwatch.conf.js
    const devServer = browser.globals.devServerURL

    browser
      .url(devServer)
      .waitForElementVisible('#app', 5000)
      .verify.title('Fruit of the Spirit')
      .verify.cssProperty('body', 'padding', '0px')
      .verify.cssProperty('body', 'margin', '0px')
      .verify.cssProperty('body', 'background-color', 'rgba(18, 166, 189, 1)')
      .verify.cssProperty('#app', 'font-weight', '300')
      .verify.cssProperty('#app', 'color', 'rgba(255, 255, 255, 1)')
      .verify.elementCount('.tab', 9)
      .verify.containsText('#love', 'Love')
      .verify.containsText('#joy', 'Joy')
      .verify.containsText('#peace', 'Peace')
      .verify.containsText('#patience', 'Patience')
      .verify.containsText('#kindness', 'Kindness')
      .verify.containsText('#goodness', 'Goodness')
      .verify.containsText('#faithfulness', 'Faithfulness')
      .verify.containsText('#gentleness', 'Gentleness')
      .verify.containsText('#selfcontrol', 'Self Control')
      .verify.cssProperty('#love', 'width', '120px')
      .verify.cssProperty('#love', 'height', '30px')
      .verify.cssProperty('#love', 'top', '7.55px')
      .verify.cssProperty('#love', 'cursor', 'pointer')
      .verify.cssProperty('#love', 'width', '120px')
      .verify.cssProperty('#love', 'font-size', '9.815px')
      .verify.cssProperty('#love', 'border-width', '1.20312px 1.20312px 1.20312px 0px')
      .verify.cssProperty('#love', 'border-top-right-radius', '2.718px')
      .verify.cssProperty('#love', 'border-color', 'rgb(255, 255, 255)')
      .verify.cssProperty('#love', 'background-color', 'rgba(223, 1, 215, 1)')
      .verify.cssProperty('#love .label', 'text-align', 'center')
      .verify.cssProperty('#love .label', 'vertical-align', 'middle')
      .verify.cssProperty('#joy', 'top', '45.3px')
      .verify.cssProperty('#selfcontrol', 'top', '309.55px')
      .verify.cssProperty('#peace', 'left', '-90.6px')
      .moveToElement('#peace', 90, 10)
      .pause(150)
      .verify.cssProperty('#peace', 'left', '-86.825px')
      .verify.cssProperty('#peace', 'transition', 'left 0.1s ease-out 0s')
      .verify.cssProperty('#peace', '-webkit-transition', 'left 0.1s ease-out 0s')
      .mouseButtonClick()
      .pause(850)
      .verify.cssProperty('#peace', 'left', '0px')
      .verify.cssProperty('#peace', 'transition', 'left 0.8s ease-out 0s')
      .verify.cssProperty('#peace', '-webkit-transition', 'left 0.8s ease-out 0s')
      .mouseButtonClick()
      .pause(850)
      .verify.cssProperty('#peace', 'left', '-86.825px')
      .moveToElement('#patience', 90, 10)
      .pause(150)
      .verify.cssProperty('#peace', 'left', '-90.6px')
      .verify.cssProperty('#peace', 'transition', 'left 0.1s ease-out 0s')
      .verify.cssProperty('#peace', '-webkit-transition', 'left 0.1s ease-out 0s')
      .mouseButtonClick()
      .pause(350)
      .mouseButtonClick()
      .pause(150)
      .mouseButtonClick()
      .pause(850)
      .moveToElement('#kindness', 90, 10)
      .verify.cssProperty('#patience', 'left', '0px')
      .mouseButtonClick()
      .pause(850)
      .verify.cssProperty('#kindness', 'left', '0px')
      .verify.cssProperty('#patience', 'left', '-90.6px')
      .end()
  }
}
